# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0005_auto_20161028_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='expressionprofiles',
            options={'managed': True},
        ),
    ]
