# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0007_expressionprofiles_experiments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextpp',
            options={'managed': True},
        ),
    ]
