# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0013_auto_20161114_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mirnas',
            options={'managed': True, 'verbose_name_plural': ' miRNAs'},
        ),
    ]
