# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0017_auto_20161114_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrnas',
            name='genome_assembly',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
