# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0020_mrnas_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionprofiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='expressionprofiles',
            name='transcript_id',
            field=models.CharField(blank=True, db_column='transcript_ID', default='transcript_id', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
