# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0024_expressionprofiles_experiments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tissues',
            old_name='tissue_name',
            new_name='Name',
        ),
    ]
