# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0025_auto_20161114_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tissues',
            old_name='Name',
            new_name='name',
        ),
    ]
