# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0029_auto_20161114_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnas',
            name='genome_assembly',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='FilTar.GenomeAssembly'),
        ),
    ]
