# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0031_auto_20161114_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrnas',
            old_name='mrna_id',
            new_name='id',
        ),
    ]
