# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0033_auto_20161116_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressionprofiles',
            name='experiments',
        ),
        migrations.DeleteModel(
            name='ExpressionProfiles',
        ),
    ]
