# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0034_auto_20161116_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpm', models.DecimalField(blank=True, db_column='TPM', decimal_places=2, max_digits=10, null=True)),
                ('experiments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FilTar.Experiments')),
                ('mrnas', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='FilTar.Mrnas')),
            ],
            options={
                'db_table': 'expression_profiles',
                'managed': True,
            },
        ),
    ]
