# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0035_expressionprofiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contextpp',
            old_name='mirna_name',
            new_name='mirna',
        ),
    ]
