# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0036_auto_20161116_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextpp',
            name='mirna',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='FilTar.Mirnas'),
        ),
    ]
