# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0039_auto_20161116_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextpp',
            name='mrna',
            field=models.CharField(blank=True, db_column='transcript_ID', max_length=20, null=True),
        ),
    ]
