# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0048_auto_20161204_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='species',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='FilTar.Species'),
        ),
        migrations.AlterField(
            model_name='genomeassembly',
            name='species',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='FilTar.Species'),
        ),
    ]
