# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilTar', '0049_auto_20161204_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiRanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, db_column='Species', max_length=20, null=True)),
                ('utr_start', models.CharField(blank=True, db_column='UTR_start', max_length=20, null=True)),
                ('utr_end', models.CharField(blank=True, db_column='UTR_end', max_length=20, null=True)),
                ('miranda_score', models.CharField(blank=True, db_column='miRanda_score', max_length=20, null=True)),
            ],
            options={
                'db_table': 'miRanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PITA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, db_column='Species', max_length=20, null=True)),
                ('utr_start', models.CharField(blank=True, db_column='UTR_Start', max_length=20, null=True)),
                ('utr_end', models.CharField(blank=True, db_column='UTR_End', max_length=20, null=True)),
                ('pita_score', models.CharField(blank=True, db_column='PITA_score', max_length=20, null=True)),
            ],
            options={
                'db_table': 'pita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test', models.CharField(blank=True, max_length=100, null=True)),
                ('for_inline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_test_models', to='FilTar.TModel')),
            ],
        ),
    ]
