# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False, 'verbose_name_plural': 'Species'},
        ),
    ]
