# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0004_auto_20161028_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrnas',
            options={'managed': False, 'verbose_name_plural': 'mRNAs'},
        ),
    ]
