# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0008_auto_20161110_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextpp',
            name='taxonomic_id'),
    ]
                     
