# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0009_auto_20161114_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tissues',
            options={'managed': True, 'verbose_name_plural': 'Tissues'},
        ),
    ]
