# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0010_auto_20161114_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tissues',
            name='id',
        ),
        migrations.AddField(
            model_name='contextpp',
            name='common_name',
            field=models.CharField(blank=True, db_column='common_name', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contextpp',
            name='tpm',
            field=models.DecimalField(blank=True, db_column='TPM', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tissues',
            name='tissue_name',
            field=models.CharField(default='tissue', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
