# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0011_auto_20161114_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'managed': True, 'verbose_name_plural': 'Species'},
        ),
    ]
