# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0012_auto_20161114_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='id',
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, default='species', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]

