# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0014_auto_20161114_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mirnas',
            name='id',
        ),
        migrations.AlterField(
            model_name='mirnas',
            name='mirna_name',
            field=models.CharField(blank=True, db_column='miRNA_name', default='mirna', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
