# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0015_auto_20161114_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrnas',
            options={'managed': True, 'verbose_name_plural': 'mRNAs'},
        ),
    ]
