# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0018_mrnas_genome_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeAssembly',
            fields=[
                ('genome_assembly', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('common_name', models.CharField(blank=True, max_length=30, null=True)),
                ('submitter', models.CharField(blank=True, max_length=30, null=True)),
                ('assembly_level', models.CharField(blank=True, max_length=30, null=True)),
                ('syonyms', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'GenomeAssembly',
                'managed': True,
                'verbose_name_plural': 'GenomeAssembly',
            },
        ),
    ]
