# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0019_genomeassembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrnas',
            name='annotation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
