# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0021_auto_20161114_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiments',
            name='id',
        ),
        migrations.AlterField(
            model_name='experiments',
            name='experiment_name',
            field=models.CharField(blank=True, default='experiments', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
