# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0027_auto_20161114_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiments',
            name='taxonomic_id',
        ),
        migrations.AddField(
            model_name='experiments',
            name='species',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='Foo.Species'),
        ),
    ]
