# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0030_auto_20161114_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirnas',
            old_name='mirna_name',
            new_name='name',
        ),
    ]
