# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0040_auto_20161116_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextpp',
            name='mrna',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='Foo.Mrnas'),
        ),
    ]
