# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0043_auto_20161116_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contextpp',
            name='tpm',
        ),
    ]
