# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foo', '0045_auto_20161124_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiments',
            name='species',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
